### ISSUE TITLE
10.04 (maybe others) can't get updates from ubuntu

### ISSUE THREAD

**Issue by bryceschober** [rafacas/vagrant-boxes#2]
For some reason I have this problem from within the current ubuntu1004-i386-plain vm:

> vagrant@vagrant:~$ ping us.archive.ubuntu.com
> PING us.archive.ubuntu.com (91.189.91.26) 56(84) bytes of data.
> 64 bytes from hanger.canonical.com (91.189.91.26): icmp_seq=1 ttl=63 time=83.9 ms
> ...sudo
> vagrant@vagrant:~$ sudo apt-get update
> ...
> Err http://us.archive.ubuntu.com lucid/restricted Packages
>   404  Not Found [IP: 91.189.91.23 80]
> ...

**Comment by rafacas** [comment]
Hi @bryceschober, there's no problem with your network. The issue is that Ubuntu 10.04 got to its end of life. That means there are no update packages for that version (Lucid) anymore. And that is the error `apt-get update` is showing.

If you go to `http://us.archive.ubuntu.com/ubuntu/dists` you will see there is no lucid directory, and that is why `apt-get` is failing to download new updates.

You have more information about Ubuntu current and end of life releases here: `https://wiki.ubuntu.com/Releases`

**Comment by bryceschober** [comment]
I see that now. It would be sweet if the "fix" from https://gist.github.com/
dergachev/f5da514802fcbbb441a1 could be applied, at least that way
additional standard packages could be installed.


<><  <><  <><
Bryce Schober

**Comment by rafacas** [comment]
That's a good idea. I'll add that fix to the next box update :)
